name: Build and Test

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "LICENSE"
      - "CHANGELOG.md"
      - "renovate.json"
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-test:
    name: Build and Test
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]
        java_version: [ 17, 19 ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: ${{ matrix.java_version }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build
        run: ./gradlew build
